In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [28]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao']=data_ingestao
df.head()

   NATBR     MKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-04-05 12:59:03.592665
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-04-05 12:59:03.592665
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-04-05 12:59:03.592665

In [29]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [32]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [37]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head()

   NATBR      MKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-05 12:47:26.189187
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-04-05 12:47:26.189187
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-05 12:47:26.189187
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-05 12:59:03.592665
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-05 12:59:03.592665

In [35]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [39]:
con.close()